import Link from "next/link";
import { ArrowRight, CreditCard, PiggyBank, Sparkles, Wallet } from "lucide-react";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Progress } from "@/components/ui/progress";
import { CategoryIcon } from "@/components/category-icon";
import { InfoButton } from "@/components/info-button";
import { RefreshButton } from "@/components/refresh-button";
import { formatMoney, formatShortDate } from "@/lib/finance/format";
import { getFinanceSnapshot } from "@/lib/finance/redbark";
import { activityLink, isCashFlowMovement, monthLabel } from "@/lib/finance/history";
import { upcomingPlan } from "@/lib/finance/planning";

export const dynamic = "force-dynamic";

export default async function HomePage() {
  const data = await getFinanceSnapshot();
  const month = data.month ?? "";
  const current = data.transactions.filter((item) => item.date.startsWith(month));
  const needsReview = current.filter((item) => isCashFlowMovement(item) && item.status === "posted" && (item.category === "Uncategorised" || item.reviewReason));
  const upcoming = upcomingPlan(data.recurring ?? [], data.plannedEvents ?? [], data.reportDate ?? "");
  const remaining = data.metrics.overallBudget - data.metrics.overallBudgetSpent;
  const usedPercent = data.metrics.overallBudget ? Math.round(data.metrics.overallBudgetSpent / data.metrics.overallBudget * 100) : 0;
  const budgets = data.budgets.filter((item) => item.limit > 0 && (item.name !== "Mortgage" || item.spent + item.pending > item.limit)).sort((a,b) => Number(b.spent + b.pending > b.limit) - Number(a.spent + a.pending > a.limit) || (b.spent + b.pending)/b.limit - (a.spent + a.pending)/a.limit).slice(0,4);
  const recent = data.transactions.filter(isCashFlowMovement).slice(0,4);
  return <div>
    <div className="mb-5 flex items-start justify-between gap-3"><div><p className="text-xs text-muted-foreground">{monthLabel(month)}</p><h1 className="mt-1 text-2xl font-semibold tracking-tight sm:text-3xl">Your household at a glance</h1></div><RefreshButton /></div>
    {data.mode === "preview" ? <p className="mb-4 rounded-lg border border-amber-200 bg-amber-50 px-3 py-2 text-xs text-amber-950">Sample household · preview data</p> : null}
    <section className="grid gap-4 lg:grid-cols-[1.2fr_1fr]" aria-label="Current position">
      <Card className="bg-primary text-primary-foreground"><CardContent className="p-6 sm:p-7"><div className="flex items-center justify-between"><p className="text-sm opacity-80">Net liquid funds</p><InfoButton title="Net liquid funds"><p>Your current offset balance minus credit card owing. The home loan balance is not included in this liquid balance.</p><p>Card repayments move money between these accounts, so they do not change net liquid funds. Mortgage payments reduce liquid funds while reducing loan debt.</p></InfoButton></div><p className="mt-1 text-4xl font-semibold tracking-tight sm:text-5xl">{formatMoney(data.metrics.netLiquid)}</p><div className="mt-6 grid grid-cols-2 gap-3">{[{type:"transaction",label:"Offset balance",value:data.metrics.offsetBalance,icon:Wallet},{type:"credit-card",label:data.metrics.cardOwing < 0 ? "Card credit" : "Card owing",value:Math.abs(data.metrics.cardOwing),icon:CreditCard}].map((item) => <Link key={item.type} href={activityLink({account:data.accounts.find((account) => account.type === item.type)?.id ?? "",flow:"all"})} className="rounded-xl bg-white/10 p-3 hover:bg-white/15"><p className="flex items-center gap-1.5 text-xs opacity-80"><item.icon className="size-3.5" />{item.label}</p><p className="mt-2 text-lg font-semibold">{formatMoney(item.value)}</p></Link>)}</div></CardContent></Card>
      <Card><CardHeader className="flex flex-row items-center justify-between pb-3"><CardTitle className="text-base">This month’s cash flow</CardTitle><InfoButton title="Monthly cash flow"><p>Posted income minus posted expenses, after refunds. Pending purchases are shown separately and count toward budgets.</p><p>Both sides of matched credit card repayments are excluded. Mortgage payments count once from the offset account. Loan-account receipts, interest and fees are not added again.</p><p>Uncategorised incoming money is included in net movement in Insights, but is not assumed to be income or a refund. Recorded surplus is not the measured change in your offset balance.</p><Link href="/insights" className="text-primary underline">Explore the underlying transactions</Link></InfoButton></CardHeader><CardContent><div className="grid grid-cols-2 gap-4">{[{label:"Income",value:data.metrics.incomeThisMonth,flow:"income"},{label:"Expenses",value:data.metrics.spentThisMonth,flow:"spending"}].map((item) => <Link key={item.flow} href={activityLink({month,flow:item.flow,status:"posted"})} className="rounded-lg py-2 hover:bg-secondary"><p className="text-xs text-muted-foreground">{item.label} →</p><p className="mt-1 text-xl font-semibold">{formatMoney(item.value)}</p></Link>)}</div><Link href="/insights" className="mt-4 flex items-center justify-between gap-3 rounded-xl bg-secondary p-4 text-sm"><span>Recorded surplus</span><strong className="text-primary">{formatMoney(data.metrics.savedThisMonth,{showSign:true})}</strong></Link><div className="mt-3 flex justify-between gap-3 text-xs text-muted-foreground"><span>Posted only</span><Link href={activityLink({month,status:"pending",flow:"spending"})} className="hover:underline">{formatMoney(data.metrics.pendingThisMonth ?? 0)} pending →</Link></div></CardContent></Card>
    </section>
    {needsReview.length ? <Link href={activityLink({month,review:needsReview.some((item) => item.category === "Uncategorised") ? "category" : "transfer",flow:"external"})} className="mt-4 flex items-center justify-between gap-3 rounded-lg border border-amber-200 bg-amber-50 px-4 py-3 text-sm text-amber-950"><span>{needsReview.length} {needsReview.length === 1 ? "transaction needs" : "transactions need"} review</span><span className="flex shrink-0 items-center gap-1 text-xs">Review <ArrowRight className="size-3" /></span></Link> : null}
    <section className="mt-4 grid grid-cols-2 gap-3" aria-label="Plan summary"><Summary href="/budgets" title={remaining >= 0 ? "Budget left" : "Over budget"} value={formatMoney(Math.abs(remaining))} detail={`${usedPercent}% used · includes pending`} icon={<PiggyBank className="size-4" />} /><Summary href="/forecast" title="3-month outlook" value={formatMoney(data.forecast[3]?.baseline ?? data.metrics.netLiquid)} detail="Net liquid · saved plan" icon={<Sparkles className="size-4" />} /></section>
    <section className="mt-4 grid gap-4 lg:grid-cols-2">
      <Card><CardHeader className="flex flex-row items-center justify-between"><CardTitle className="text-base">Budget pulse</CardTitle><Link href="/budgets" className="text-xs text-primary hover:underline">View all →</Link></CardHeader><CardContent className="space-y-4">{budgets.map((budget) => { const used=budget.spent+budget.pending; return <Link key={budget.id} href={`/budgets?category=${encodeURIComponent(budget.name)}`} className="flex items-center gap-3 rounded-lg hover:bg-secondary"><CategoryIcon name={budget.icon} color={budget.color} /><div className="min-w-0 flex-1"><div className="mb-2 flex justify-between gap-2 text-xs"><span className="font-medium">{budget.name}</span><span className={used > budget.limit ? "text-orange-700" : "text-muted-foreground"}>{formatMoney(used)} / {formatMoney(budget.limit)}</span></div><Progress className="h-1.5" value={Math.min(100,Math.max(0,used/budget.limit*100))} /></div></Link>; })}{!budgets.length ? <Link href="/budgets" className="text-sm text-primary">Set your category targets →</Link> : null}</CardContent></Card>
      <Card><CardHeader className="flex flex-row items-center justify-between"><CardTitle className="text-base">Recent activity</CardTitle><Link href="/activity" className="text-xs text-primary hover:underline">View all →</Link></CardHeader><CardContent className="divide-y">{recent.map((item) => <Link key={item.id} className="flex justify-between gap-3 py-2.5 text-sm" href={activityLink({month:item.date.slice(0,7),search:item.merchantName ?? item.description})}><div className="min-w-0"><p className="truncate font-medium">{item.merchantName ?? item.description}</p><p className="text-xs text-muted-foreground">{formatShortDate(item.date)} · {item.category}{item.status === "pending" ? " · pending" : ""}</p></div><strong className="shrink-0">{formatMoney(item.amount)}</strong></Link>)}</CardContent></Card>
    </section>
    <Card className="mt-4"><CardHeader className="flex flex-row items-center justify-between"><div className="flex items-center gap-1"><CardTitle className="text-base">Upcoming</CardTitle><InfoButton title="Upcoming plan"><p>Expected recurring income, bills and known one-offs in the next 30 days, starting tomorrow. These are your planned dates, not bank-confirmed unpaid bills; an item may have been paid early.</p><p>Manage the complete schedule in Forecast.</p></InfoButton></div><Link href="/forecast" className="text-xs text-primary hover:underline">View plan →</Link></CardHeader><CardContent className="grid gap-3 sm:grid-cols-3">{upcoming.slice(0,3).map((item) => <Link href="/forecast" className="flex items-center justify-between gap-2 rounded-xl border p-3 text-xs" key={item.id}><div className="min-w-0"><p className="text-muted-foreground">{formatShortDate(item.date)}</p><p className="mt-1 truncate font-medium">{item.name}</p></div><strong className="shrink-0">{formatMoney(item.amount)}</strong></Link>)}{!upcoming.length ? <Link href="/forecast" className="text-sm text-primary">Add your income and bill schedule →</Link> : null}</CardContent></Card>
  </div>;
}
function Summary({href,title,value,detail,icon}:{href:string;title:string;value:string;detail:string;icon:React.ReactNode}) { return <Link className="min-w-0 rounded-xl focus-visible:outline-2" href={href}><Card className="h-full hover:bg-secondary"><CardContent className="p-4"><div className="flex items-center gap-2 text-xs text-muted-foreground">{icon}{title}</div><p className="mt-2 break-words text-xl font-semibold">{value}</p><p className="mt-1 text-[11px] text-muted-foreground">{detail}</p></CardContent></Card></Link>; }
