"use client";

import Link from "next/link";
import { activityLink, monthlyHistory, monthLabel, expenseContribution, isCashFlowMovement } from "@/lib/finance/history";
import { categoryChange, reviewSummary } from "@/lib/finance/planning";
import { formatMoney } from "@/lib/finance/format";
import type { BudgetLine, FinanceTransaction } from "@/lib/finance/types";
import { Card, CardContent, CardHeader, CardTitle } from "./ui/card";
import { InfoButton } from "./info-button";
import { useHousehold } from "./household-context";

export function InsightHighlights({ transactions, month, currentMonth, asOf, person, budgets }: { transactions: FinanceTransaction[]; month: string; currentMonth: string; asOf: string; person: string; budgets: BudgetLine[] }) {
  const { personLabel } = useHousehold();
  const selected = transactions.filter((item) => item.date.startsWith(month) && (person === "all" || item.person === person));
  const quality = reviewSummary(selected);
  const history = monthlyHistory(transactions, currentMonth, person);
  const changes = categoryChange(transactions, month, person, month === currentMonth ? Number(asOf.slice(8,10)) : 31);
  const previousAvailable = transactions.some((item) => item.date.startsWith(changes.previousMonth) && Number(item.date.slice(8,10)) <= changes.day && item.status === "posted" && isCashFlowMovement(item) && (person === "all" || person === item.person));
  const prior = history.filter((row) => !row.current && row.month > history[0]?.month && row.count > 0);
  const targets = person !== "all" ? [] : budgets.filter((budget) => budget.limit > 0 && budget.name !== "Uncategorised").map((budget) => {
    const values = prior.map((row) => transactions.filter((item) => item.date.startsWith(row.month) && item.category === budget.name && !item.isTransfer && item.status === "posted" && item.currency.toLowerCase() === "aud").reduce((sum,item) => sum + expenseContribution(item),0));
    const average = values.length ? Math.round(values.reduce((sum,value) => sum + value,0) / values.length) : null;
    return { ...budget, average, gap: average === null ? 0 : average - budget.limit };
  }).filter((item) => item.average !== null && Math.abs(item.gap) >= Math.max(2000,item.limit * 0.2)).sort((a,b) => Math.abs(b.gap) - Math.abs(a.gap)).slice(0,3);
  return <div className="mt-4 space-y-4">
    <div className="rounded-xl border bg-secondary/40 p-4 text-xs leading-5"><div className="flex items-center justify-between gap-2"><p className="font-medium">{quality.coverage}% categorised · {formatMoney(quality.unknownSpend)} uncategorised</p><InfoButton title="Category coverage"><p>Coverage is measured by posted purchase value, not transaction count. Categories include suggestions and are not proof of review.</p><p>{quality.unknownPeople} transactions have no person assigned. Imported history may be incomplete; repayments and loan-account entries are excluded.</p></InfoButton></div><Link className="mt-1 inline-block text-primary underline" href={activityLink({ month, review: "category", person })}>Review this month’s categories →</Link></div>
    <div className="grid gap-4 lg:grid-cols-2">
      <Card><CardHeader><CardTitle className="text-base">What changed from last month?</CardTitle><p className="text-xs text-muted-foreground">{month === currentMonth ? `Compare days 1–${changes.day} in both months.` : "Posted expenses across both months."}</p></CardHeader><CardContent className="space-y-3">{previousAvailable ? changes.rows.filter((row) => row.change !== 0).slice(0,3).map((row) => <div key={row.category}><div className="flex justify-between gap-3 text-sm"><span>{row.category}</span><strong className={row.change > 0 ? "text-orange-700" : "text-emerald-700"}>{formatMoney(row.change,{showSign:true})}</strong></div><div className="mt-1 flex flex-wrap justify-between gap-2 text-xs"><Link className="text-primary underline" href={activityLink({ month: changes.previousMonth, category: row.category, person, status:"posted", flow:"spending", to: `${changes.previousMonth}-${String(Math.min(changes.day,new Date(Number(changes.previousMonth.slice(0,4)),Number(changes.previousMonth.slice(5,7)),0).getDate())).padStart(2,"0")}` })}>{monthLabel(changes.previousMonth)}: {formatMoney(row.previous)}</Link><Link className="text-primary underline" href={activityLink({ month, category: row.category, person, status:"posted", flow:"spending", to:`${month}-${String(Math.min(changes.day,new Date(Number(month.slice(0,4)),Number(month.slice(5,7)),0).getDate())).padStart(2,"0")}` })}>{monthLabel(month)}: {formatMoney(row.current)}</Link></div></div>) : <p className="text-sm text-muted-foreground">No comparable posted history for these dates in the previous month.</p>}</CardContent></Card>
      <Card><CardHeader><div className="flex items-center justify-between"><CardTitle className="text-base">Budget reality check</CardTitle><InfoButton title="Budget reality check"><p>Targets are compared with {prior.length} prior imported months, excluding the first imported month and current month.</p><p>Uncategorised purchases can understate averages. These are review prompts, not automatic changes. Check history before adopting a target.</p></InfoButton></div></CardHeader><CardContent className="space-y-3">{targets.map((item) => <Link href={`/budgets?category=${encodeURIComponent(item.name)}`} key={item.id} className="block rounded-lg p-2 hover:bg-secondary"><p className="text-sm font-medium">{item.name}: {formatMoney(item.average ?? 0)} average vs {formatMoney(item.limit)} target</p><p className="mt-1 text-xs text-muted-foreground">{item.gap > 0 ? "Past expenses exceed this target." : "Past expenses are below this target."} Check the history before changing it →</p></Link>)}{!targets.length ? <p className="text-sm text-muted-foreground">{person !== "all" ? "Select the whole household to compare budget targets." : !prior.length ? "More prior months are needed for a useful comparison." : "No category differs from its target by 20% and at least $20."}</p> : null}</CardContent></Card>
    </div>
    <details className="rounded-xl border p-4 text-xs"><summary className="cursor-pointer font-semibold">Spending by person · {monthLabel(month)}</summary><div className="mt-3 grid gap-3 sm:grid-cols-4">{["Stefan","Partner","Shared","Unknown"].map((owner) => { const amount = selected.filter((item) => item.person === owner && item.status === "posted" && item.currency.toLowerCase() === "aud").reduce((sum,item) => sum + expenseContribution(item),0); return <Link key={owner} className="rounded-lg bg-secondary p-3" href={activityLink({month,person:owner,status:"posted",flow:"spending"})}><p>{owner === "Unknown" ? "Unassigned" : personLabel(owner)}</p><strong className="mt-1 block text-sm">{formatMoney(amount)}</strong></Link>; })}</div><p className="mt-3 text-muted-foreground">Person assignment is entered in Harbour; the bank feed does not identify the additional cardholder.</p></details>
  </div>;
}
